- name: debug
  debug:
    var: deploy_user_password

- name: Create deploy user
  user:
    name: "{{ deploy_user_name }}"
    password: "{{ deploy_user_password | password_hash('sha512') }}"
    groups:
      - sudo
    append: yes
    shell: /bin/bash
    create_home: yes
    state: present
    update_password: always
