---
- name: Configure SSH daemon
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} {{ item.value }}'
    state: present
    create: yes
  loop:
    - { key: 'PermitRootLogin', value: 'no' }
    - { key: 'PasswordAuthentication', value: 'no' }
    - { key: 'AllowUsers', value: '{{ deploy_user_name }}' }
  notify: Restart ssh
